CREATE DATABASE SERRALINHASAEREASDB
USE SERRALINHASAEREASDB

-- Creating table clients
CREATE TABLE CLIENTS(
ID INT IDENTITY(1,1) NOT NULL,
CPF VARCHAR(11) NOT NULL,
CLIENT_NAME VARCHAR(100) NOT NULL,
NICKNAME VARCHAR(100) NOT NULL,
CEP VARCHAR (11) NOT NULL,
STREET VARCHAR(100) NOT NULL,
DISTRICT VARCHAR (100) NOT NULL,
NUMBER INT NOT NULL,
COMPLEMENT VARCHAR(100) NOT NULL
CONSTRAINT PK_CLIENTS PRIMARY KEY (ID)
)

SELECT * FROM CLIENTS

-- Creating table tickets
CREATE TABLE TICKETS(
ID INT IDENTITY(1,1) NOT NULL,
DEPART_FROM VARCHAR(100) NOT NULL,
FLYING_TO VARCHAR(100) NOT NULL,
PRICE DECIMAL NOT NULL,
DEPART_FROM_DATE DATETIME NOT NULL,
FLYING_TO_DATE DATETIME NOT NULL
CONSTRAINT PK_TICKETS PRIMARY KEY (ID)
)


SELECT * FROM TICKETS

-- Creating table travels
CREATE TABLE TRAVELS(
ID INT IDENTITY (1,1) NOT NULL,
TICKET_CODE VARCHAR(6) NOT NULL,
ORDERTIME DATETIME NOT NULL,
TOTALPRICE DECIMAL NOT NULL,
CLIENT_ID INT NOT NULL,
GOING_AND_RETURN BIT NULL,
TICKET_GOING INT NOT NULL,
TICKET_RETURN INT NULL,
CONSTRAINT PK_TRAVELS PRIMARY KEY (ID),
CONSTRAINT FK_CLIENT_ID FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID),
CONSTRAINT FK_TICKET_GOING FOREIGN KEY (TICKET_GOING) REFERENCES TICKETS (ID),
CONSTRAINT FK_TICKET_RETURN FOREIGN KEY (TICKET_RETURN) REFERENCES TICKETS (ID),
)

SELECT * FROM TRAVELS


-- Testing 
INSERT INTO CLIENTS VALUES
('123456', 'Lucas', 'Zanon', '8852000', 'Rua 1', 'Bairro maneiro', '1', 'Ap 1'),
('456789', 'Frodo', 'Baggins', '8852001', 'Rua 2', 'Bairro médio', '2', 'Ap 2'),
('654321', 'Gandalf', 'The Grey', '8852002', 'Rua 3', 'Bairro dos magos', '3', 'Ap 4'),
('987654', 'Samwise', 'Gamgee', '8852003', 'Rua 4', 'Bairro legal', '4', 'Ap 5')
SELECT * FROM CLIENTS

--DELETE FROM CLIENTS
--DROP TABLE CLIENTS

INSERT INTO TICKETS VALUES 
('Porto Alegre', 'Rio de Janeiro', 400, '02/02/2022', '03/03/2022'),
('Rio de Janeiro', 'Alegre', 450, '03/02/2022', '03/04/2022'),
('São José dos Campos', 'São Luis', 1750, '02/02/2022', '02/03/2022'),
('Manaus', 'Rio de Janeiro', 1600, '03/02/2022', '03/04/2022')
SELECT * FROM TICKETS

--DELETE FROM TICKETS
--DROP TABLE TICKETS

--Ida e volta
INSERT INTO TRAVELS VALUES 
('QWERTY', '02/02/2022', 2000, 1, 1, 1, 2)
--Apenas ida
INSERT INTO TRAVELS (TICKET_CODE, ORDERTIME, TOTALPRICE, CLIENT_ID, GOING_AND_RETURN, TICKET_GOING) VALUES 
('ASDFGH', '02/03/2022', 450, 1, 0, 3),
('ZXCVBN', '06/03/2022', 680, 2, 0, 4)

SELECT * FROM TRAVELS

--DELETE FROM TRAVELS
--DROP TABLE TRAVELS









